### ISSUE TITLE
crmservice_transient_keys option created with incorrect default value type

### ISSUE THREAD

**Issue by nturbanov** [CRM-service/CRM-service-wp-forms#9]
[The option 'crmservice_transient_keys' is created with a default value of an empty string](https://github.com/CRM-service/CRM-service-wp-forms/blob/master/classes/class-helper.php#L227) instead of an empty array. And thus, the transient keys are not correctly stored in the option.

Noticed this as PHP's error log contains this stuff

`PHP Warning:  Illegal string offset 'crmservice_api_response_664cee17fb72d1acf46521a1efa7e50a' in .../crm-service-wp-forms/classes/class-helper.php on line 232`

**Comment by timiwahalahti** [comment]
Thanks for reporting @nturbanov! I'll fix this and release a new version with it tomorrow latest.

**Comment by timiwahalahti** [comment]
Just to let you know, fix is now also released as a version 1.2.2 in wordpress.org repository. https://plugins.trac.wordpress.org/changeset/2236380
